# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.cache/wt [current_project]
set_property parent.project_path D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivado2018.3/Projects/vending_machinecc/vending_machine.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new [current_fileset]
read_verilog D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/admin_mode_defs.vh
read_verilog -library xil_defaultlib {
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/admin_engine.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/admin_mode_subsystem.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/audio_pwm_driver.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/auth_engine.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/buzzer_controller.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/buzzer_request_adapter.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/data_manager.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/error_manager.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/input_event_router.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/key_decoder.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/led_controller.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/main_mode_fsm.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/matrix_keypad_scanner.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/numeric_input_buffer.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/order_timer.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/reset_sync.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/sale_engine.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/sevenseg_controller.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/tick_gen.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/ui_snapshot_packer.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/vga_system.v
  D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/sources_1/new/TopModule.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/constrs_1/new/ego1_vending_machine.xdc
set_property used_in_implementation false [get_files D:/Vivado2018.3/Projects/vending_machinecc/vending_machine.srcs/constrs_1/new/ego1_vending_machine.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TopModule -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TopModule.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TopModule_utilization_synth.rpt -pb TopModule_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
